### ISSUE TITLE
Flask 서버 + Postman으로 JSON 데이터를 주고 받고, 서버에서 모델 raw data 형식에 맞게 포매팅

### ISSUE THREAD

**Issue by Yuuraa** [FreshTomato-BoostCamp/demo-dialogue-state-tracking#2]
### 해야 하는 일

- HTTP request에 대한 간단한 이해 & Flask
    - [https://meetup.toast.com/posts/92](https://meetup.toast.com/posts/92)
    - https://flask.palletsprojects.com/en/2.0.x/api/
- Flask app 만들고, HTTP POST 요청으로 받은 JSON 데이터 확인
- 받은 텍스트 데이터들을 서버 측에 쌓아서 dialogue history 만들기
- dialogue history, 이번에 들어온 턴 까지의 데이터를 활용해 WoS 형식에 맞춰 저장하기
- 구현된 Jupyternotebook 파일을 web_practice/flask_{이름}.ipynb 로 올리기

---

### 클라이언트에서 보낼 데이터 형태
- JSON
  - user: 사용자 아이디
  - message: 사용자가 보낸 메시지

---
### 생각해 볼 것
- dialogue_history를 서버에서 처리 후 메모리 상에 저장할 것인지, 혹은 클라이언트 측에서 함쳐진 형태로 보내는 게 나을지
- feature를 뽑을 때 시간이 오래 걸리는데, 바로 이전 턴에서 뽑은 feature를 이용할 방법은 무엇일지

**Comment by iloveslowfood** [comment]
짱이다

**Comment by Yuuraa** [comment]
끝
